version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=${API_KEY}
      - API_URL=${API_URL:-https://openrouter.ai/api/v1/chat/completions}
      - MODEL_NAME=${MODEL_NAME:-meta-llama/llama-4-maverick:free}
    restart: unless-stopped

  frontend:
    build:
      context: ./vue_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped